#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobile.KI.Shadow.Trainer.Droid.Resource", IsApplication=true)]

namespace Mobile.KI.Shadow.Trainer.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aganos = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arbiter = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int aria = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cinder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int eyedol = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int fulgore = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int gargos = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int glacius = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int hisako = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int jago = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int kanra = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int kimwu = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int maya = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int mira = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int omen = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int orchid = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int raam = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int rash = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int riptor = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int sabrewulf = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int sadira = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int shadowjago = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int spinal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int thunder = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tjcombo = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tusk = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int GridChars = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int GridImage = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int GridMoves = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int GridText = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int VideoPlayer = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int chkBeep = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int cmdPlay = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int lblFrames = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int lblScore = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int seekBar = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int textItem = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int txtSearch = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CharacterListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ImageBorder = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Moves = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TextViewItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Trainer = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int aironryozan = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ankleslicer = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int batteringram = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int beep = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int bladedash = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int bladedemon = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int boltstrike = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int boneshaker = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int coldshoulder = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int combobreaker = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int crushingboltstrike = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int crushingdestroyer = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int crushingshoulder = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int crushingstompstrike = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int darkdemise = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int darkdrift = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int decimation = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int demonslide = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int dragondance = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int explosivearc = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int eyelaser = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int firecat = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int firecracker = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int fission = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int flickflack = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int flyingknee = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int furiousflurry = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int hail = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int immortalspirit = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int inferno = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int jumpingslash = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int lasersword = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int leapkick = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int lockout = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int mercysdemise = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int naturaldisaster = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int oblivion = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int one = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int onryozan = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int plasmaport = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int powerline = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int pulverize = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int raggededge = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int reckoning = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int shotgunblitz = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int shouldercharge = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int skullsplitter = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int small = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int soulsword = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int stompstrike = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int Strings = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int swarm = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int tailflip = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int talonrake = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int three = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int trailblazer = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int tremor = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int trephine = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int triplax = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int truthseeker = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int tumblekick = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int two = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int whirl = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int widowsbite = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int windkick = 2130968640;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
	}
}
#pragma warning restore 1591
